project: 
  type: website
  output-dir: "." 

website:
  title: "Jack Gramlich"
  navbar:
    background: "#603f77"
    pinned: true
    left:
      - text: Blog
        href: blog-listing.qmd
  page-footer: 
    center: "Powered with GitHub and Quarto<br>Â© Jack Gramlich, 2024"

format:
  html:
    theme: 
      light: flatly # flatly sandstone yeti united litera journal
      dark: darkly #  darkly cyborg slate solra superhero
    mainfont: system-ui; 
    highlight-style: atom-one  # atom-one espresso
    css: styles.css
    toc: false
    include-after-body: target_blank.html

